name: Tistory RSS Sync

on:
  schedule:
    - cron: '0 * * * *'  # 매 시간 정각 실행 (UTC 기준 → 한국은 매시 9분쯤)
  workflow_dispatch:     # 수동 실행도 허용

jobs:
  sync_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Feedparser
        run: pip install feedparser

      - name: Run RSS Sync Script
        run: python scripts/rss_to_md.py

      - name: Commit & Push
        env:
          TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
          git config --global user.name "VictorBot"
          git config --global user.email "victor-jeon-1998@users.noreply.github.com"
          git add .
          git commit -m "auto: update from Tistory RSS" || echo "nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/VICTOR-JEON-1998/victor-tech-posts.git HEAD:main

